// for Payment page

export const POST_NEW_ADDRESS = 'POST_NEW_ADDRESS'
export const POST_NEW_CARD = 'POST_NEW_CARD'
export const SELECT_CURR_ADDRESS = 'SELECT_CURR_ADDRESS'
export const SELECT_CURR_CARD = 'SELECT_CURR_CARD'
export const DELETE_ADDRESS = 'DELETE_ADDRESS'
export const DELETE_CARD = 'DELETE_CARD'